### ISSUE TITLE
Add compatibility with Scala 2.10 and 2.11

### ISSUE THREAD

**Issue by ilaborie** [yoshiyoshifujii/kamon-cloudwatch#2]

**Comment by yoshiyoshifujii** [comment]
released
- https://github.com/yoshiyoshifujii/kamon-cloudwatch/releases/tag/v0.2.1
- https://search.maven.org/artifact/com.github.yoshiyoshifujii/kamon-cloudwatch_2.10/0.2.1/jar
- https://search.maven.org/artifact/com.github.yoshiyoshifujii/kamon-cloudwatch_2.11/0.2.1/jar
